export default {
  REQUEST_MARKETS_LIST: 'REQUEST_MARKETS_LIST',
  RECEIVE_MARKETS_LIST: 'RECEIVE_MARKETS_LIST',
  RESET_MARKETS_LIST: 'RESET_MARKETS_LIST',
  REQUEST_MARKETS_ITEM: 'REQUEST_MARKETS_ITEM',
  RECEIVE_MARKETS_ITEM: 'RECEIVE_MARKETS_ITEM',
  RESET_MARKETS_ITEM: 'RESET_MARKETS_ITEM',
  UPDATE_START_MARKETS_ITEM: 'UPDATE_START_MARKETS_ITEM',
  UPDATE_DONE_MARKETS_ITEM: 'UPDATE_DONE_MARKETS_ITEM',
  SET_USER: 'SET_USER',
  RESET_USER: 'RESET_USER'
}
